name: Docker Image CI

on:
  push:
    branches: [ deploy ]

jobs:

  build:

    runs-on: ubuntu-latest

    outputs:
      short_ref: ${{ steps.vars.outputs.short_ref }}
      build_number: ${{ steps.buildnumber.outputs.build_number }}

    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: docker build . --file Dockerfile.oss --tag docker.pkg.github.com/churchpool/nginx-bucket-proxy-${{ steps.vars.outputs.short_ref }}:0.1.$BUILD_NUMBER

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Push Docker image to Github package registry
      run: docker push docker.pkg.github.com/churchpool/nginx-bucket-proxy-${{ steps.vars.outputs.short_ref }}:0.1.$BUILD_NUMBER

    - name: Login to OTC
      run: docker login -u eu-de@${{ secrets.OTC_ACCESS_KEY}} -p ${{ secrets.OTC_LOGIN_KEY}} swr.eu-de.otc.t-systems.com

    - name: Tag Docker image
      run: docker tag docker.pkg.github.com/churchpool/nginx-bucket-proxy-${{ steps.vars.outputs.short_ref }}:0.1.$BUILD_NUMBER swr.eu-de.otc.t-systems.com/churchpool-api/nginx-bucket-proxy-${{ steps.vars.outputs.short_ref }}:0.1.$BUILD_NUMBER

    - name: Push Docker image to OTC
      run: docker push swr.eu-de.otc.t-systems.com/churchpool-api/nginx-bucket-proxy-${{ steps.vars.outputs.short_ref }}:0.1.$BUILD_NUMBER
